jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          key: ${{ runner.os }}-sonar
          path: ~/.sonar/cache
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          path: ~/.gradle/caches
          restore-keys: ${{ runner.os }}-gradle
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        name: Build and analyze
        run: ./gradlew build sonarqube --info
name: Build
'on':
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - master